SignUp page
zuri-training/auth-wiki-team7 pull request #57
Opened 2022-07-29 21:25 UTC by Victorious-Toluwalope

2022-07-31 07:50 UTC, spykelionel requested changes
Great work. You are doing well.

See comments

2022-07-31 07:50 UTC, spykelionel commented on frontend/css/signup.css
> +}
Must use class names to avoid conflicts with styling from other pages. Use class naming conventions please. 

Also check base.css file for base styles.

Nice work.

2022-07-31 07:50 UTC, spykelionel commented on frontend/css/signup.css
> +} */
Remove any unused styles to tidy the file. Refactor this. The header will be included in all pages. No need to include the styles in your file. Thanks. Also check base.css file for base styles

2022-07-31 07:50 UTC, spykelionel commented on frontend/css/signup.css
> +}
Also check base.css file for base styles. Don't use global styles.

The base.css file is at frontend/css

2022-07-31 07:50 UTC, spykelionel commented on frontend/pages/signup.html
> +      <title>Sign Up</title>
Include base.css after title here.

_<link rel="stylesheet" href="../css/base.css">_

2022-07-31 07:50 UTC, spykelionel commented on frontend/pages/signup.html
> +
Remove empty lines

2022-07-31 07:50 UTC, spykelionel commented on frontend/pages/signup.html
> +    </header> -->
Remove this. A header will be included when all work will be merged

2022-07-31 07:50 UTC, spykelionel commented on frontend/pages/signup.html
> +                <option value="English (Pidgin)">English (Pidgin)</option>
This language would sound invalid. This should be removed too

2022-07-31 07:50 UTC, spykelionel commented on frontend/pages/signup.html
> +        </div> -->
Remove unused to tidy the work

2022-07-31 17:04 UTC, ToluwalaseAfolajimi requested changes
Hi Lionel,
I just checked the sign up page, and I think if we make few changes, we'll be good to go.
The search input color for one is grey and not black - from the text to the icon and frame.
Also the features (About, products, documentation) font weights are not as in the design.
Lastly, I noticed that the footer/bottom bar is not as it is in the design.
That will be all for now. 
Thank you.

2022-08-03 02:21 UTC, Victorious-Toluwalope commented on frontend/pages/signup.html
> +      <title>Sign Up</title>
Done

2022-08-03 02:21 UTC, Victorious-Toluwalope commented on frontend/pages/signup.html
> +
Done

2022-08-03 19:34 UTC, spykelionel commented
Pr moved to Center Alignment. Check here #56

2022-08-03 19:34 UTC, closed without merging