like and unlike
zuri-training/auth-wiki-team7 pull request #75
Opened 2022-08-02 17:34 UTC by Tech-Genius

like and unlike

2022-08-02 17:43 UTC, echefulouis approved these changes

2022-08-04 11:14 UTC, spykelionel requested changes

2022-08-04 12:07 UTC, spykelionel requested changes
Delete all files in media

2022-08-04 12:07 UTC, spykelionel commented on backend/media_cdn/media/readme.txt
> +==================================================================================================
Delete all files in the media folder

2022-08-04 12:07 UTC, spykelionel commented on backend/static/js/ajax.js
> +
What's this ? Empty lines

2022-08-04 13:01 UTC, spykelionel approved these changes

2022-08-04 13:02 UTC, merged