Bn host
zuri-training/auth-wiki-team7 pull request #93
Opened 2022-08-06 17:21 UTC by Tech-Genius

2022-08-06 17:43 UTC, echefulouis reviewed
Please resolve conflicts

2022-08-06 20:50 UTC, spykelionel requested changes
Delete all highlight.js files. We'll get it from the cdn

2022-08-06 20:50 UTC, spykelionel commented on backend/base.html
> +<script src="{% static 'js/highlight.min.js' %}"></script>
No need to download. Will get it from a CDN. You can remove this both from static dir

2022-08-06 20:50 UTC, spykelionel commented on backend/base.html
> +<script>hljs.highlightAll();</script>
Here too. Remove this line 27

2022-08-06 20:50 UTC, spykelionel commented on backend/library/admin.py
> +
Short version. 

_models = [Post, Comment]

admin.sites.register(_models)
#but all good 👍

2022-08-06 20:50 UTC, spykelionel commented on backend/static/css/login.css
> +body{
Will need to give it a class of lp-body so it doesn't affect other pages. Also in login.html

2022-08-06 20:50 UTC, spykelionel commented on backend/static/css/style.css
> +    display: flex;
Delete this file. All styles already in landing.css.

#duplicate

2022-08-06 20:50 UTC, spykelionel commented on backend/static/css/styles/a11y-dark.min.css
> +pre code.hljs{display:block;overflow-x:auto;padding:1em}code.hljs{padding:3px 5px}/*!
Delete this file. Will get it from CDN

2022-08-07 09:15 UTC, spykelionel approved these changes
- [x] - Delete highlight.js related files. We'll get it from the cdn

2022-08-07 09:15 UTC, merged